#!/usr/bin/env python3
"""Build the readable compound registry and check cross-references.

Usage:
    python3 scripts/build_registry.py            # writes research/registry.md
    python3 scripts/build_registry.py --check    # validate only, no write

research/registry.json is the hand-maintained part: identity, taxonomy and the
page plan. This script joins it with the evidence counts and ChEMBL data that
scripts/fetch_evidence.py stored in each data/compounds/<slug>.json, and writes
research/registry.md as the table people actually read.

It also enforces the one integrity rule the registry exists for: every stack
component, comparison side, class name and pilot wave must resolve. A dangling
reference here becomes a broken comparison table on a page.

Standard library only.
"""
from __future__ import annotations

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
REGISTRY = ROOT / "research" / "registry.json"
RECORDS = ROOT / "data" / "compounds"
OUT = ROOT / "research" / "registry.md"
WAVES = {1, 2, 3}


def load_evidence() -> dict[str, dict]:
    """slug -> evidence_summary + tier from fetched records, where they exist."""
    found: dict[str, dict] = {}
    for path in sorted(RECORDS.glob("*.json")):
        try:
            rec = json.loads(path.read_text(encoding="utf-8"))
        except ValueError:
            continue
        if rec.get("type") != "compound":
            continue
        found[rec["slug"]] = {
            "tier": rec.get("evidence_tier"),
            "status": rec.get("status"),
            "sources": len(rec.get("sources") or []),
            **(rec.get("evidence_summary") or {}),
        }
    return found


def check(reg: dict) -> list[str]:
    errors: list[str] = []
    slugs = {c["slug"] for c in reg["compounds"]}
    classes = set(reg["classes"])
    for c in reg["compounds"]:
        if c["class"] not in classes:
            errors.append(f"compound {c['slug']}: unknown class {c['class']!r}")
        if c.get("pilot_wave") not in WAVES:
            errors.append(f"compound {c['slug']}: pilot_wave must be 1, 2 or 3")
    for s in reg["stacks"]:
        for comp in s["components"]:
            if comp not in slugs:
                errors.append(f"stack {s['slug']}: component {comp!r} is not a registered compound")
        if len(s["components"]) < 2:
            errors.append(f"stack {s['slug']}: needs at least two components")
    for cmp_ in reg["comparisons"]:
        for side in cmp_["sides"]:
            if side not in slugs:
                errors.append(f"comparison {cmp_['slug']}: side {side!r} is not a registered compound")
        if len(cmp_["sides"]) != 2:
            errors.append(f"comparison {cmp_['slug']}: needs exactly two sides")
    seen: set[str] = set()
    for kind in ("compounds", "stacks", "comparisons", "tools"):
        for item in reg[kind]:
            if item["slug"] in seen:
                errors.append(f"duplicate slug across the plan: {item['slug']}")
            seen.add(item["slug"])
    unused = classes - {c["class"] for c in reg["compounds"]}
    for u in sorted(unused):
        errors.append(f"class {u!r} has no compounds")
    return errors


def peers(reg: dict, slug: str) -> list[str]:
    cls = next(c["class"] for c in reg["compounds"] if c["slug"] == slug)
    return sorted(c["slug"] for c in reg["compounds"] if c["class"] == cls and c["slug"] != slug)


def fmt(n: object) -> str:
    return f"{n:,}" if isinstance(n, int) else "—"


def build(reg: dict, ev: dict[str, dict]) -> str:
    out: list[str] = []
    out.append("# Compound registry\n")
    out.append("Generated by `scripts/build_registry.py` from `research/registry.json` and the fetched records in "
               "`data/compounds/`. Edit the JSON, not this file. Class and target assignments are "
               f"**{reg.get('class_status', 'proposed')}** pending owner confirmation.\n")
    out.append("Identity and taxonomy live here. Evidence claims never do; a half-life or a dose belongs in a "
               "record as a claim with a source, not in a table cell.\n")

    out.append("## Compounds\n")
    out.append("| Wave | Compound | Class | Target | Type | aa | Pubs | RCTs | Trials | Tier | ChEMBL | Phase | Record |")
    out.append("|---|---|---|---|---|---|---|---|---|---|---|---|---|")
    for c in sorted(reg["compounds"], key=lambda c: (c["pilot_wave"], c["slug"])):
        e = ev.get(c["slug"], {})
        pubs = (e.get("publications") or {})
        ch = e.get("chembl") or {}
        phase = ch.get("max_phase")
        out.append(
            f"| {c['pilot_wave']} | `{c['slug']}` | {c['class']} | {c['target']} | {c['molecule_type']} | "
            f"{c['length_aa'] if c['length_aa'] is not None else '?'} | {fmt(pubs.get('total'))} | "
            f"{fmt(pubs.get('randomized_controlled_trials'))} | {fmt(pubs.get('clinical_trials'))} | "
            f"{('`' + e['tier'] + '`') if e.get('tier') else '—'} | {ch.get('chembl_id') or '—'} | "
            f"{(f'{phase:g}' if isinstance(phase, (int, float)) else '—')} | {e.get('status') or 'not fetched'} |"
        )
    out.append("")
    missing = [c["slug"] for c in reg["compounds"] if c["slug"] not in ev]
    if missing:
        out.append(f"Not yet fetched ({len(missing)}): " + ", ".join(f"`{m}`" for m in missing) + "\n")

    out.append("## Classes\n")
    out.append("| Class | Description | Members |")
    out.append("|---|---|---|")
    for name, desc in reg["classes"].items():
        members = sorted(c["slug"] for c in reg["compounds"] if c["class"] == name)
        out.append(f"| `{name}` | {desc} | {', '.join(f'`{m}`' for m in members)} |")
    out.append("")

    out.append("## Stacks\n")
    out.append("| Wave | Stack | Components | Component tiers | Rationale |")
    out.append("|---|---|---|---|---|")
    for s in sorted(reg["stacks"], key=lambda s: (s["pilot_wave"], s["slug"])):
        tiers = ", ".join(f"`{ev.get(x, {}).get('tier') or '?'}`" for x in s["components"])
        out.append(f"| {s['pilot_wave']} | `{s['slug']}` | {', '.join(f'`{x}`' for x in s['components'])} | {tiers} | {s['rationale']} |")
    out.append("")

    out.append("## Comparisons\n")
    out.append("| Wave | Comparison | Sides | Rationale |")
    out.append("|---|---|---|---|")
    for c in sorted(reg["comparisons"], key=lambda c: (c["pilot_wave"], c["slug"])):
        out.append(f"| {c['pilot_wave']} | `{c['slug']}` | {' vs '.join(f'`{x}`' for x in c['sides'])} | {c['rationale']} |")
    out.append("")

    out.append("## Tools\n")
    out.append("| Wave | Tool | Computes | Refuses |")
    out.append("|---|---|---|---|")
    for t in sorted(reg["tools"], key=lambda t: (t["pilot_wave"], t["slug"])):
        out.append(f"| {t['pilot_wave']} | `{t['slug']}` | {t['computes']} | {t['refuses']} |")
    out.append("")

    counts = {w: sum(1 for c in reg["compounds"] if c["pilot_wave"] == w) for w in sorted(WAVES)}
    sc = {w: sum(1 for s in reg["stacks"] if s["pilot_wave"] == w) for w in sorted(WAVES)}
    cc = {w: sum(1 for c in reg["comparisons"] if c["pilot_wave"] == w) for w in sorted(WAVES)}
    tc = {w: sum(1 for t in reg["tools"] if t["pilot_wave"] == w) for w in sorted(WAVES)}
    out.append("## Page plan by wave\n")
    out.append("| Wave | Compounds | Stacks | Comparisons | Tools | Cumulative programmatic pages |")
    out.append("|---|---|---|---|---|---|")
    cum = 0
    for w in sorted(WAVES):
        cum += counts[w] + sc[w] + cc[w] + tc[w]
        out.append(f"| {w} | {counts[w]} | {sc[w]} | {cc[w]} | {tc[w]} | {cum} |")
    out.append("")
    out.append("Wave 1 stays under the 50-page indexation-review cap in `docs/PRD.md`; the full plan stays under the "
               "100-page content-audit gate in `docs/page-template-spec.md`. Cycle pages are deliberately absent.\n")

    out.append("## Peers by class (feeds section 19 and `related`)\n")
    for c in sorted(reg["compounds"], key=lambda c: c["slug"]):
        p = peers(reg, c["slug"])
        out.append(f"- `{c['slug']}`: " + (", ".join(f"`{x}`" for x in p) if p else "*no peers in class*"))
    out.append("")
    return "\n".join(out)


def main(argv: list[str]) -> int:
    reg = json.loads(REGISTRY.read_text(encoding="utf-8"))
    errors = check(reg)
    if errors:
        print("REGISTRY CHECK FAILED")
        for e in errors:
            print(f"- {e}")
        return 1
    if "--check" in argv:
        print(f"Registry check passed ({len(reg['compounds'])} compounds, {len(reg['stacks'])} stacks, "
              f"{len(reg['comparisons'])} comparisons, {len(reg['tools'])} tools).")
        return 0
    ev = load_evidence()
    OUT.write_text(build(reg, ev), encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)}: {len(ev)}/{len(reg['compounds'])} compounds have fetched evidence.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
